version: '3.5'

services:
  account-api:
    image: microservices-workshop/account-api
    ports:
      - 8084:8080
    networks:
      - workshop-example

  payment-api:
    image: microservices-workshop/payment-api
    ports:
      - 8085:8080
    networks:
      - workshop-example

  notification-consumer:
    image: microservices-workshop/notification-consumer
    networks:
      - workshop-example

  shipping-api:
    image: microservices-workshop/shipping-api
    ports:
      - 8086:8080
    networks:
      - workshop-example

networks:
  workshop-example: