global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'prometheus:9090'
  - job_name: inventory 
    metrics_path: /prometheus
    static_configs:
      - targets:
        - inventory-api:8080